import type { CableSpec, ComponentPort } from './types';

const powerPorts: ComponentPort[] = [
  { id: 'a', kind: 'power', direction: 'inout', label: { ar: 'طرف أ', en: 'End A', ku: 'سەری A', tr: 'Uç A' } },
  { id: 'b', kind: 'power', direction: 'inout', label: { ar: 'طرف ب', en: 'End B', ku: 'سەری B', tr: 'Uç B' } },
];

const busPorts: ComponentPort[] = [
  { id: 'a', kind: 'bus', direction: 'inout', label: { ar: 'طرف أ', en: 'End A', ku: 'سەری A', tr: 'Uç A' } },
  { id: 'b', kind: 'bus', direction: 'inout', label: { ar: 'طرف ب', en: 'End B', ku: 'سەری B', tr: 'Uç B' } },
];

const signalPorts: ComponentPort[] = [
  { id: 'a', kind: 'signal', direction: 'inout', label: { ar: 'طرف أ', en: 'End A', ku: 'سەری A', tr: 'Uç A' } },
  { id: 'b', kind: 'signal', direction: 'inout', label: { ar: 'طرف ب', en: 'End B', ku: 'سەری B', tr: 'Uç B' } },
];

/**
 * Copper LV cable ampacities are aligned to IEC 60364-5-52 reference method
 * C (clipped direct) for PVC/XLPE multicore — representative values for the
 * sizing engine. Aluminium values use the ~0.78 conductivity ratio.
 */
export const CABLES: CableSpec[] = [
  // ----- LV copper power cables (XLPE/PVC) -----
  ...([
    { csa: 1.5, amp: 19.5, r: 12.1, x: 0.11, w: 95, cost: 0.9 },
    { csa: 2.5, amp: 27, r: 7.41, x: 0.1, w: 140, cost: 1.4 },
    { csa: 4, amp: 36, r: 4.61, x: 0.1, w: 200, cost: 2.1 },
    { csa: 6, amp: 46, r: 3.08, x: 0.1, w: 280, cost: 3.0 },
    { csa: 10, amp: 63, r: 1.83, x: 0.094, w: 430, cost: 4.8 },
    { csa: 16, amp: 85, r: 1.15, x: 0.09, w: 640, cost: 7.2 },
    { csa: 25, amp: 112, r: 0.727, x: 0.086, w: 980, cost: 11.5 },
    { csa: 35, amp: 138, r: 0.524, x: 0.083, w: 1300, cost: 15.8 },
    { csa: 50, amp: 168, r: 0.387, x: 0.083, w: 1750, cost: 21.5 },
    { csa: 70, amp: 213, r: 0.268, x: 0.082, w: 2400, cost: 30.0 },
    { csa: 95, amp: 258, r: 0.193, x: 0.082, w: 3200, cost: 41.0 },
    { csa: 120, amp: 299, r: 0.153, x: 0.08, w: 3950, cost: 52.0 },
    { csa: 185, amp: 379, r: 0.0991, x: 0.08, w: 5900, cost: 78.0 },
    { csa: 240, amp: 446, r: 0.0754, x: 0.079, w: 7600, cost: 102.0 },
  ] as const).map<CableSpec>((c) => ({
    id: `cable-lv-cu-${c.csa}`,
    domain: 'cable',
    category: 'LV',
    name: {
      ar: `كابل جهد منخفض نحاس ${c.csa} مم²`,
      en: `LV Copper Cable ${c.csa} mm²`,
      ku: `کێبڵی LV مس ${c.csa} mm²`,
      tr: `AG Bakır Kablo ${c.csa} mm²`,
    },
    manufacturer: 'Nexans',
    model: `N2XH ${c.csa}`,
    standards: ['IEC 60364', 'IEC 60287', 'IEC 60332'],
    ports: powerPorts,
    icon: 'Cable',
    color: '#f59e0b',
    conductorMaterial: 'copper',
    coreCount: 4,
    csaMm2: c.csa,
    voltageRating: 1000,
    ampacityA: c.amp,
    resistanceOhmPerKm: c.r,
    reactanceOhmPerKm: c.x,
    weightKgPerKm: c.w,
    costPerMeter: c.cost,
    fireResistant: false,
  })),

  // ----- LV aluminium power cables -----
  ...([
    { csa: 16, amp: 66, r: 1.91, x: 0.09, w: 380, cost: 4.1 },
    { csa: 25, amp: 87, r: 1.2, x: 0.086, w: 540, cost: 6.0 },
    { csa: 50, amp: 131, r: 0.641, x: 0.083, w: 920, cost: 11.0 },
    { csa: 95, amp: 201, r: 0.32, x: 0.082, w: 1600, cost: 20.0 },
    { csa: 185, amp: 295, r: 0.164, x: 0.08, w: 3000, cost: 38.0 },
    { csa: 240, amp: 347, r: 0.125, x: 0.079, w: 3850, cost: 49.0 },
  ] as const).map<CableSpec>((c) => ({
    id: `cable-lv-al-${c.csa}`,
    domain: 'cable',
    category: 'LV',
    name: {
      ar: `كابل جهد منخفض ألمنيوم ${c.csa} مم²`,
      en: `LV Aluminium Cable ${c.csa} mm²`,
      ku: `کێبڵی LV ئەلمنیۆم ${c.csa} mm²`,
      tr: `AG Alüminyum Kablo ${c.csa} mm²`,
    },
    manufacturer: 'Prysmian',
    model: `AL-XLPE ${c.csa}`,
    standards: ['IEC 60364', 'IEC 60287'],
    ports: powerPorts,
    icon: 'Cable',
    color: '#d97706',
    conductorMaterial: 'aluminium',
    coreCount: 4,
    csaMm2: c.csa,
    voltageRating: 1000,
    ampacityA: c.amp,
    resistanceOhmPerKm: c.r,
    reactanceOhmPerKm: c.x,
    weightKgPerKm: c.w,
    costPerMeter: c.cost,
    fireResistant: false,
  })),

  // ----- MV cable -----
  {
    id: 'cable-mv-cu-95',
    domain: 'cable',
    category: 'MV',
    name: { ar: 'كابل جهد متوسط 95 مم²', en: 'MV Cable 95 mm²', ku: 'کێبڵی MV ٩٥ mm²', tr: 'OG Kablo 95 mm²' },
    manufacturer: 'Nexans',
    model: 'A2XS(F)2Y 12/20kV',
    standards: ['IEC 60287'],
    ports: powerPorts,
    icon: 'Cable',
    color: '#b45309',
    conductorMaterial: 'copper',
    coreCount: 3,
    csaMm2: 95,
    voltageRating: 20000,
    ampacityA: 290,
    resistanceOhmPerKm: 0.193,
    reactanceOhmPerKm: 0.12,
    weightKgPerKm: 4200,
    costPerMeter: 95,
    fireResistant: false,
  },

  // ----- Fire resistant / fire alarm -----
  {
    id: 'cable-fire-2x1.5',
    domain: 'cable',
    category: 'FIRE',
    name: { ar: 'كابل مقاوم للحريق 2×1.5', en: 'Fire Resistant Cable 2×1.5', ku: 'کێبڵی بەرگری ئاگر 2×1.5', tr: 'Yangına Dayanıklı Kablo 2×1.5' },
    manufacturer: 'Draka',
    model: 'FireBurn FE180 2x1.5',
    standards: ['IEC 60332'],
    ports: powerPorts,
    icon: 'Flame',
    color: '#ef4444',
    conductorMaterial: 'copper',
    coreCount: 2,
    csaMm2: 1.5,
    voltageRating: 500,
    ampacityA: 18,
    resistanceOhmPerKm: 12.1,
    reactanceOhmPerKm: 0.11,
    weightKgPerKm: 110,
    costPerMeter: 2.6,
    fireResistant: true,
  },
  {
    id: 'cable-fire-alarm-2x1.5',
    domain: 'cable',
    category: 'FIRE_ALARM',
    name: { ar: 'كابل إنذار حريق 2×1.5', en: 'Fire Alarm Cable 2×1.5', ku: 'کێبڵی ئاگاداری ئاگر 2×1.5', tr: 'Yangın Alarm Kablosu 2×1.5' },
    manufacturer: 'Belden',
    model: 'FA 2x1.5 red',
    standards: ['IEC 60332', 'NFPA 70'],
    ports: signalPorts,
    icon: 'BellRing',
    color: '#dc2626',
    conductorMaterial: 'copper',
    coreCount: 2,
    csaMm2: 1.5,
    voltageRating: 300,
    ampacityA: 15,
    resistanceOhmPerKm: 12.1,
    reactanceOhmPerKm: 0.11,
    weightKgPerKm: 90,
    costPerMeter: 1.9,
    fireResistant: true,
  },

  // ----- Control cable -----
  {
    id: 'cable-control-7x1.5',
    domain: 'cable',
    category: 'CONTROL',
    name: { ar: 'كابل تحكم 7×1.5', en: 'Control Cable 7×1.5', ku: 'کێبڵی کۆنتڕۆڵ 7×1.5', tr: 'Kumanda Kablosu 7×1.5' },
    manufacturer: 'Lapp',
    model: 'ÖLFLEX 7G1.5',
    standards: ['IEC 60364'],
    ports: signalPorts,
    icon: 'Cable',
    color: '#64748b',
    conductorMaterial: 'copper',
    coreCount: 7,
    csaMm2: 1.5,
    voltageRating: 500,
    ampacityA: 18,
    resistanceOhmPerKm: 12.1,
    reactanceOhmPerKm: 0.11,
    weightKgPerKm: 170,
    costPerMeter: 3.2,
    fireResistant: false,
  },

  // ----- Data / comms -----
  {
    id: 'cable-cat6',
    domain: 'cable',
    category: 'DATA',
    name: { ar: 'كابل شبكة CAT6', en: 'CAT6 Network Cable', ku: 'کێبڵی تۆڕ CAT6', tr: 'CAT6 Ağ Kablosu' },
    manufacturer: 'Commscope',
    model: 'UTP CAT6',
    standards: [],
    ports: signalPorts,
    icon: 'Network',
    color: '#3b82f6',
    conductorMaterial: 'copper',
    coreCount: 8,
    csaMm2: 0.2,
    voltageRating: 60,
    ampacityA: 1,
    resistanceOhmPerKm: 90,
    reactanceOhmPerKm: 0,
    weightKgPerKm: 42,
    costPerMeter: 1.1,
    fireResistant: false,
  },
  {
    id: 'cable-cat6a',
    domain: 'cable',
    category: 'DATA',
    name: { ar: 'كابل شبكة CAT6A', en: 'CAT6A Network Cable', ku: 'کێبڵی تۆڕ CAT6A', tr: 'CAT6A Ağ Kablosu' },
    manufacturer: 'Commscope',
    model: 'F/UTP CAT6A',
    standards: [],
    ports: signalPorts,
    icon: 'Network',
    color: '#2563eb',
    conductorMaterial: 'copper',
    coreCount: 8,
    csaMm2: 0.25,
    voltageRating: 60,
    ampacityA: 1,
    resistanceOhmPerKm: 78,
    reactanceOhmPerKm: 0,
    weightKgPerKm: 58,
    costPerMeter: 1.8,
    fireResistant: false,
  },
  {
    id: 'cable-cat7',
    domain: 'cable',
    category: 'DATA',
    name: { ar: 'كابل شبكة CAT7', en: 'CAT7 Network Cable', ku: 'کێبڵی تۆڕ CAT7', tr: 'CAT7 Ağ Kablosu' },
    manufacturer: 'Draka',
    model: 'S/FTP CAT7',
    standards: [],
    ports: signalPorts,
    icon: 'Network',
    color: '#1d4ed8',
    conductorMaterial: 'copper',
    coreCount: 8,
    csaMm2: 0.25,
    voltageRating: 60,
    ampacityA: 1,
    resistanceOhmPerKm: 70,
    reactanceOhmPerKm: 0,
    weightKgPerKm: 70,
    costPerMeter: 2.4,
    fireResistant: false,
  },
  {
    id: 'cable-fiber',
    domain: 'cable',
    category: 'DATA',
    name: { ar: 'كابل ألياف ضوئية', en: 'Fiber Optic Cable', ku: 'کێبڵی فایبەری ئۆپتیک', tr: 'Fiber Optik Kablo' },
    manufacturer: 'Corning',
    model: 'SMF-28 12C',
    standards: [],
    ports: signalPorts,
    icon: 'Spline',
    color: '#06b6d4',
    conductorMaterial: 'copper',
    coreCount: 12,
    csaMm2: 0,
    voltageRating: 0,
    ampacityA: 0,
    resistanceOhmPerKm: 0,
    reactanceOhmPerKm: 0,
    weightKgPerKm: 35,
    costPerMeter: 3.5,
    fireResistant: false,
  },
  {
    id: 'cable-hdmi',
    domain: 'cable',
    category: 'AV',
    name: { ar: 'كابل HDMI', en: 'HDMI Cable', ku: 'کێبڵی HDMI', tr: 'HDMI Kablo' },
    manufacturer: 'Kramer',
    model: 'HDMI 2.1',
    standards: [],
    ports: signalPorts,
    icon: 'MonitorPlay',
    color: '#8b5cf6',
    conductorMaterial: 'copper',
    coreCount: 19,
    csaMm2: 0.1,
    voltageRating: 5,
    ampacityA: 0.5,
    resistanceOhmPerKm: 100,
    reactanceOhmPerKm: 0,
    weightKgPerKm: 80,
    costPerMeter: 4.0,
    fireResistant: false,
  },
  {
    id: 'cable-speaker',
    domain: 'cable',
    category: 'AV',
    name: { ar: 'كابل سماعات 2×2.5', en: 'Speaker Cable 2×2.5', ku: 'کێبڵی بڵندگۆ 2×2.5', tr: 'Hoparlör Kablosu 2×2.5' },
    manufacturer: 'QED',
    model: 'XT25 2x2.5',
    standards: [],
    ports: signalPorts,
    icon: 'Volume2',
    color: '#a855f7',
    conductorMaterial: 'copper',
    coreCount: 2,
    csaMm2: 2.5,
    voltageRating: 100,
    ampacityA: 10,
    resistanceOhmPerKm: 7.41,
    reactanceOhmPerKm: 0,
    weightKgPerKm: 60,
    costPerMeter: 2.2,
    fireResistant: false,
  },
  // ----- KNX bus cable -----
  {
    id: 'cable-knx-bus',
    domain: 'cable',
    category: 'BUS',
    name: { ar: 'كابل ناقل KNX', en: 'KNX Bus Cable', ku: 'کێبڵی باسی KNX', tr: 'KNX Bus Kablosu' },
    manufacturer: 'Hager',
    model: 'TG018 2x2x0.8',
    standards: ['KNX'],
    ports: busPorts,
    icon: 'Cable',
    color: '#16a34a',
    conductorMaterial: 'copper',
    coreCount: 4,
    csaMm2: 0.5,
    voltageRating: 30,
    ampacityA: 1,
    resistanceOhmPerKm: 73.5,
    reactanceOhmPerKm: 0,
    weightKgPerKm: 30,
    costPerMeter: 0.8,
    fireResistant: false,
  },
];
