import type { HvacSpec, ComponentPort } from './types';

const inPort: ComponentPort[] = [
  { id: 'in', kind: 'power', direction: 'in', label: { ar: 'دخل كهرباء', en: 'Power In', ku: 'هێزی هاتن', tr: 'Güç Girişi' } },
  { id: 'ctrl', kind: 'control', direction: 'in', label: { ar: 'تحكم', en: 'Control', ku: 'کۆنتڕۆڵ', tr: 'Kumanda' } },
];

export const HVAC: HvacSpec[] = [
  {
    id: 'hvac-split-3.5',
    domain: 'hvac',
    category: 'SPLIT',
    name: { ar: 'مكيف سبليت 12000 BTU', en: 'Split AC 12000 BTU', ku: 'سپلیتی 12000 BTU', tr: 'Split Klima 12000 BTU' },
    manufacturer: 'Daikin',
    model: 'FTXM35',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'AirVent',
    color: '#38bdf8',
    hvacType: 'SPLIT',
    coolingKw: 3.5,
    heatingKw: 4.0,
    inputKw: 1.0,
    cop: 4.0,
    eer: 3.5,
    voltage: 230,
    phases: 1,
  },
  {
    id: 'hvac-vrf-40',
    domain: 'hvac',
    category: 'VRF',
    name: { ar: 'نظام VRF 40 كيلوواط', en: 'VRF System 40kW', ku: 'سیستەمی VRF 40kW', tr: 'VRF Sistemi 40kW' },
    manufacturer: 'Mitsubishi',
    model: 'City Multi R2',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'Snowflake',
    color: '#0ea5e9',
    hvacType: 'VRF',
    coolingKw: 40,
    heatingKw: 45,
    inputKw: 11.5,
    cop: 3.9,
    eer: 3.48,
    voltage: 400,
    phases: 3,
    maxIndoorUnits: 20,
  },
  {
    id: 'hvac-vrf-outdoor-28',
    domain: 'hvac',
    category: 'VRF_OUTDOOR',
    name: { ar: 'وحدة VRF خارجية 28 كW', en: 'VRF Outdoor 28kW', ku: 'VRF دەرەکی 28kW', tr: 'VRF Dış Ünite 28kW' },
    manufacturer: 'Mitsubishi',
    model: 'PUHY-P280',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'Snowflake',
    color: '#0369a1',
    hvacType: 'VRF_OUTDOOR',
    coolingKw: 28,
    heatingKw: 31.5,
    inputKw: 8.2,
    cop: 3.85,
    eer: 3.4,
    voltage: 400,
    phases: 3,
    maxIndoorUnits: 16,
  },
  {
    id: 'hvac-vrf-outdoor-56',
    domain: 'hvac',
    category: 'VRF_OUTDOOR',
    name: { ar: 'وحدة VRF خارجية 56 كW', en: 'VRF Outdoor 56kW', ku: 'VRF دەرەکی 56kW', tr: 'VRF Dış Ünite 56kW' },
    manufacturer: 'Mitsubishi',
    model: 'PUHY-P560',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'Snowflake',
    color: '#075985',
    hvacType: 'VRF_OUTDOOR',
    coolingKw: 56,
    heatingKw: 63,
    inputKw: 16,
    cop: 3.9,
    eer: 3.5,
    voltage: 400,
    phases: 3,
    maxIndoorUnits: 32,
  },
  {
    id: 'hvac-vrf-indoor-2.2',
    domain: 'hvac',
    category: 'VRF_INDOOR',
    name: { ar: 'VRF داخلي حائط 2.2 كW', en: 'VRF Wall Indoor 2.2kW', ku: 'VRF ناوەوە 2.2kW', tr: 'VRF Duvar İç 2.2kW' },
    manufacturer: 'Mitsubishi',
    model: 'PKA-RP71',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'AirVent',
    color: '#38bdf8',
    hvacType: 'VRF_INDOOR',
    coolingKw: 2.2,
    heatingKw: 2.5,
    inputKw: 0.05,
    cop: 4.5,
    eer: 4.0,
    voltage: 230,
    phases: 1,
    vrfIndoorStyle: 'wall',
  },
  {
    id: 'hvac-vrf-indoor-3.5',
    domain: 'hvac',
    category: 'VRF_INDOOR',
    name: { ar: 'VRF داخلي حائط 3.5 كW', en: 'VRF Wall Indoor 3.5kW', ku: 'VRF ناوەوە 3.5kW', tr: 'VRF Duvar İç 3.5kW' },
    manufacturer: 'Mitsubishi',
    model: 'PKA-RP100',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'AirVent',
    color: '#0ea5e9',
    hvacType: 'VRF_INDOOR',
    coolingKw: 3.5,
    heatingKw: 4.0,
    inputKw: 0.06,
    cop: 4.5,
    eer: 4.0,
    voltage: 230,
    phases: 1,
    vrfIndoorStyle: 'wall',
  },
  {
    id: 'hvac-vrf-indoor-5.0',
    domain: 'hvac',
    category: 'VRF_INDOOR',
    name: { ar: 'VRF دكت 5 كW', en: 'VRF Duct Indoor 5kW', ku: 'VRF داکت 5kW', tr: 'VRF Kanal İç 5kW' },
    manufacturer: 'Mitsubishi',
    model: 'PEAD-M50',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'Wind',
    color: '#0284c7',
    hvacType: 'VRF_INDOOR',
    coolingKw: 5.0,
    heatingKw: 5.6,
    inputKw: 0.08,
    cop: 4.2,
    eer: 3.8,
    voltage: 230,
    phases: 1,
    vrfIndoorStyle: 'duct',
  },
  {
    id: 'hvac-vrf-indoor-7.1',
    domain: 'hvac',
    category: 'VRF_INDOOR',
    name: { ar: 'VRF كاسيت 7.1 كW', en: 'VRF Cassette Indoor 7.1kW', ku: 'VRF کاسێت 7.1kW', tr: 'VRF Kaset İç 7.1kW' },
    manufacturer: 'Mitsubishi',
    model: 'PLFY-P71',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'Fan',
    color: '#06b6d4',
    hvacType: 'VRF_INDOOR',
    coolingKw: 7.1,
    heatingKw: 8.0,
    inputKw: 0.1,
    cop: 4.0,
    eer: 3.6,
    voltage: 230,
    phases: 1,
    vrfIndoorStyle: 'cassette',
  },
  {
    id: 'hvac-vrf-indoor-10.0',
    domain: 'hvac',
    category: 'VRF_INDOOR',
    name: { ar: 'VRF دكت 10 كW', en: 'VRF Duct Indoor 10kW', ku: 'VRF داکت 10kW', tr: 'VRF Kanal İç 10kW' },
    manufacturer: 'Mitsubishi',
    model: 'PEAD-M100',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'Wind',
    color: '#0891b2',
    hvacType: 'VRF_INDOOR',
    coolingKw: 10.0,
    heatingKw: 11.2,
    inputKw: 0.12,
    cop: 4.0,
    eer: 3.6,
    voltage: 230,
    phases: 1,
    vrfIndoorStyle: 'duct',
  },
  {
    id: 'hvac-chiller-300',
    domain: 'hvac',
    category: 'CHILLER',
    name: { ar: 'مبرد مياه 300 كيلوواط', en: 'Water Chiller 300kW', ku: 'چیلەری ئاو 300kW', tr: 'Su Soğutmalı Chiller 300kW' },
    manufacturer: 'Carrier',
    model: '30XA',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'Thermometer',
    color: '#0284c7',
    hvacType: 'CHILLER',
    coolingKw: 300,
    heatingKw: 0,
    inputKw: 95,
    cop: 0,
    eer: 3.16,
    voltage: 400,
    phases: 3,
  },
  {
    id: 'hvac-fcu-5',
    domain: 'hvac',
    category: 'FCU',
    name: { ar: 'وحدة ملف مروحة FCU', en: 'Fan Coil Unit', ku: 'یەکەی فان کۆیل', tr: 'Fan Coil Ünitesi' },
    manufacturer: 'Daikin',
    model: 'FWB',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'Fan',
    color: '#22d3ee',
    hvacType: 'FCU',
    coolingKw: 5,
    heatingKw: 6,
    inputKw: 0.15,
    cop: 40,
    eer: 33,
    voltage: 230,
    phases: 1,
  },
  {
    id: 'hvac-ahu-50',
    domain: 'hvac',
    category: 'AHU',
    name: { ar: 'وحدة مناولة هواء AHU', en: 'Air Handling Unit', ku: 'یەکەی AHU', tr: 'Klima Santrali (AHU)' },
    manufacturer: 'Systemair',
    model: 'Geniox 22',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'Wind',
    color: '#06b6d4',
    hvacType: 'AHU',
    coolingKw: 50,
    heatingKw: 60,
    inputKw: 7.5,
    cop: 8,
    eer: 6.7,
    voltage: 400,
    phases: 3,
  },
  {
    id: 'hvac-package-30',
    domain: 'hvac',
    category: 'PACKAGE',
    name: { ar: 'وحدة باكج 30 كيلوواط', en: 'Package Unit 30kW', ku: 'یەکەی پاکیج 30kW', tr: 'Paket Klima 30kW' },
    manufacturer: 'Trane',
    model: 'Voyager',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'Container',
    color: '#0891b2',
    hvacType: 'PACKAGE',
    coolingKw: 30,
    heatingKw: 32,
    inputKw: 9.5,
    cop: 3.4,
    eer: 3.16,
    voltage: 400,
    phases: 3,
  },
  {
    id: 'hvac-heatpump-12',
    domain: 'hvac',
    category: 'HEAT_PUMP',
    name: { ar: 'مضخة حرارية 12 كيلوواط', en: 'Heat Pump 12kW', ku: 'پەمپی گەرمی 12kW', tr: 'Isı Pompası 12kW' },
    manufacturer: 'Bosch',
    model: 'Compress 7000i',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'Flame',
    color: '#f97316',
    hvacType: 'HEAT_PUMP',
    coolingKw: 12,
    heatingKw: 14,
    inputKw: 3,
    cop: 4.6,
    eer: 4.0,
    voltage: 400,
    phases: 3,
  },
  {
    id: 'hvac-underfloor-3',
    domain: 'hvac',
    category: 'UNDERFLOOR',
    name: { ar: 'تدفئة أرضية 3 كيلوواط', en: 'Underfloor Heating 3kW', ku: 'گەرمکردنی ژێر زەوی 3kW', tr: 'Yerden Isıtma 3kW' },
    manufacturer: 'Danfoss',
    model: 'ECmat',
    standards: ['ASHRAE'],
    ports: inPort,
    icon: 'Grid3x3',
    color: '#fb7185',
    hvacType: 'UNDERFLOOR',
    coolingKw: 0,
    heatingKw: 3,
    inputKw: 3,
    cop: 1,
    eer: 0,
    voltage: 230,
    phases: 1,
  },
];
