import type { ProtectionSpec, ComponentPort } from './types';

const linePorts = (poles: number): ComponentPort[] => [
  { id: 'line', kind: 'power', direction: 'in', label: { ar: 'دخل', en: 'Line', ku: 'هێڵ', tr: 'Hat' } },
  { id: 'load', kind: 'power', direction: 'out', label: { ar: 'خرج', en: 'Load', ku: 'بار', tr: 'Yük' } },
];

const ratings = [6, 10, 16, 20, 25, 32, 40, 50, 63] as const;

export const PROTECTION: ProtectionSpec[] = [
  // ----- MCB (IEC 60898) curve C -----
  ...ratings.map<ProtectionSpec>((r) => ({
    id: `mcb-c${r}`,
    domain: 'protection',
    category: 'MCB',
    name: {
      ar: `قاطع MCB ${r}A منحنى C`,
      en: `MCB ${r}A Curve C`,
      ku: `MCB ${r}A کرڤی C`,
      tr: `MCB ${r}A C Eğrisi`,
    },
    manufacturer: 'Schneider',
    model: `Acti9 iC60N C${r}`,
    standards: ['IEC 60898'],
    ports: linePorts(1),
    icon: 'ToggleRight',
    color: '#10b981',
    protectionType: 'MCB',
    ratedCurrentA: r,
    poles: 1,
    breakingCapacityKA: 6,
    tripCurve: 'C',
    residualSensitivityMa: null,
    adjustable: false,
  })),

  // ----- MCCB (IEC 60947) -----
  ...([100, 160, 250, 400, 630] as const).map<ProtectionSpec>((r) => ({
    id: `mccb-${r}`,
    domain: 'protection',
    category: 'MCCB',
    name: {
      ar: `قاطع MCCB ${r}A`,
      en: `MCCB ${r}A`,
      ku: `MCCB ${r}A`,
      tr: `MCCB ${r}A`,
    },
    manufacturer: 'ABB',
    model: `Tmax XT ${r}`,
    standards: ['IEC 60947'],
    ports: linePorts(3),
    icon: 'SquareStack',
    color: '#059669',
    protectionType: 'MCCB',
    ratedCurrentA: r,
    poles: 3,
    breakingCapacityKA: 36,
    tripCurve: 'NA',
    residualSensitivityMa: null,
    adjustable: true,
  })),

  // ----- ACB -----
  {
    id: 'acb-1600',
    domain: 'protection',
    category: 'ACB',
    name: { ar: 'قاطع هوائي ACB 1600A', en: 'ACB 1600A', ku: 'ACB 1600A', tr: 'ACB 1600A' },
    manufacturer: 'Schneider',
    model: 'MasterPact MTZ2 16',
    standards: ['IEC 60947'],
    ports: linePorts(4),
    icon: 'Frame',
    color: '#047857',
    protectionType: 'ACB',
    ratedCurrentA: 1600,
    poles: 4,
    breakingCapacityKA: 65,
    tripCurve: 'NA',
    residualSensitivityMa: null,
    adjustable: true,
  },

  // ----- RCCB -----
  {
    id: 'rccb-40-30',
    domain: 'protection',
    category: 'RCCB',
    name: { ar: 'قاطع تسرب RCCB 40A 30mA', en: 'RCCB 40A 30mA', ku: 'RCCB 40A 30mA', tr: 'RCCB 40A 30mA' },
    manufacturer: 'Hager',
    model: 'CDA440D',
    standards: ['IEC 60947'],
    ports: linePorts(2),
    icon: 'ShieldAlert',
    color: '#0d9488',
    protectionType: 'RCCB',
    ratedCurrentA: 40,
    poles: 2,
    breakingCapacityKA: 6,
    tripCurve: 'NA',
    residualSensitivityMa: 30,
    adjustable: false,
  },

  // ----- RCBO -----
  {
    id: 'rcbo-16-30',
    domain: 'protection',
    category: 'RCBO',
    name: { ar: 'قاطع RCBO 16A 30mA', en: 'RCBO 16A 30mA', ku: 'RCBO 16A 30mA', tr: 'RCBO 16A 30mA' },
    manufacturer: 'Schneider',
    model: 'Acti9 iC60 RCBO',
    standards: ['IEC 60898', 'IEC 60947'],
    ports: linePorts(2),
    icon: 'ShieldCheck',
    color: '#14b8a6',
    protectionType: 'RCBO',
    ratedCurrentA: 16,
    poles: 2,
    breakingCapacityKA: 6,
    tripCurve: 'C',
    residualSensitivityMa: 30,
    adjustable: false,
  },

  // ----- MPCB -----
  {
    id: 'mpcb-16',
    domain: 'protection',
    category: 'MPCB',
    name: { ar: 'حامي محرك MPCB 9-16A', en: 'MPCB 9-16A', ku: 'MPCB 9-16A', tr: 'MPCB 9-16A' },
    manufacturer: 'ABB',
    model: 'MS132-16',
    standards: ['IEC 60947'],
    ports: linePorts(3),
    icon: 'Fan',
    color: '#0891b2',
    protectionType: 'MPCB',
    ratedCurrentA: 16,
    poles: 3,
    breakingCapacityKA: 50,
    tripCurve: 'NA',
    residualSensitivityMa: null,
    adjustable: true,
  },

  // ----- Fuse -----
  {
    id: 'fuse-gg-63',
    domain: 'protection',
    category: 'FUSE',
    name: { ar: 'منصهر gG 63A', en: 'Fuse gG 63A', ku: 'فیوزی gG 63A', tr: 'Sigorta gG 63A' },
    manufacturer: 'Eaton',
    model: 'NH00 63A gG',
    standards: ['IEC 60947'],
    ports: linePorts(1),
    icon: 'Zap',
    color: '#0e7490',
    protectionType: 'FUSE',
    ratedCurrentA: 63,
    poles: 1,
    breakingCapacityKA: 120,
    tripCurve: 'NA',
    residualSensitivityMa: null,
    adjustable: false,
  },

  // ----- SPD -----
  {
    id: 'spd-t2',
    domain: 'protection',
    category: 'SPD',
    name: { ar: 'واقي صواعق SPD نوع 2', en: 'SPD Type 2', ku: 'SPD جۆری 2', tr: 'SPD Tip 2' },
    manufacturer: 'DEHN',
    model: 'DEHNguard M TNS',
    standards: ['IEC 60364'],
    ports: linePorts(4),
    icon: 'Zap',
    color: '#155e75',
    protectionType: 'SPD',
    ratedCurrentA: 0,
    poles: 4,
    breakingCapacityKA: 0,
    tripCurve: 'NA',
    residualSensitivityMa: null,
    adjustable: false,
  },
];
