import type { SourceSpec, LoadSpec, ComponentPort } from './types';

const outPort: ComponentPort[] = [
  { id: 'out', kind: 'power', direction: 'out', label: { ar: 'خرج', en: 'Output', ku: 'دەرچوون', tr: 'Çıkış' } },
];

const inPort: ComponentPort[] = [
  { id: 'in', kind: 'power', direction: 'in', label: { ar: 'دخل', en: 'Input', ku: 'هاتن', tr: 'Giriş' } },
];

export const SOURCES: SourceSpec[] = [
  {
    id: 'src-utility-400',
    domain: 'source',
    category: 'UTILITY',
    name: { ar: 'مصدر الشبكة العامة', en: 'Utility Supply', ku: 'سەرچاوەی تۆڕ', tr: 'Şebeke Beslemesi' },
    manufacturer: 'Grid',
    model: 'TN-S 400V',
    standards: ['IEC 60364'],
    ports: outPort,
    icon: 'PlugZap',
    color: '#6366f1',
    sourceType: 'UTILITY',
    voltage: 400,
    phases: 3,
    ratedKva: 250,
    powerFactor: 0.95,
    efficiency: 1,
    scContributionKA: 25,
  },
  {
    id: 'src-generator-100',
    domain: 'source',
    category: 'GENERATOR',
    name: { ar: 'مولد ديزل 100 ك.ف.أ', en: 'Diesel Generator 100kVA', ku: 'جێنەرەیتەری دیزڵ 100kVA', tr: 'Dizel Jeneratör 100kVA' },
    manufacturer: 'Cummins',
    model: 'C100D5',
    standards: ['IEC 60364'],
    ports: outPort,
    icon: 'Power',
    color: '#4f46e5',
    sourceType: 'GENERATOR',
    voltage: 400,
    phases: 3,
    ratedKva: 100,
    powerFactor: 0.8,
    efficiency: 0.9,
    scContributionKA: 4,
  },
  {
    id: 'src-ups-20',
    domain: 'source',
    category: 'UPS',
    name: { ar: 'مزود طاقة UPS 20 ك.ف.أ', en: 'UPS 20kVA', ku: 'UPS 20kVA', tr: 'UPS 20kVA' },
    manufacturer: 'Eaton',
    model: '93PS-20',
    standards: ['IEC 60364'],
    ports: [...inPort, ...outPort],
    icon: 'BatteryCharging',
    color: '#7c3aed',
    sourceType: 'UPS',
    voltage: 400,
    phases: 3,
    ratedKva: 20,
    powerFactor: 0.9,
    efficiency: 0.96,
    scContributionKA: 1,
  },
  {
    id: 'src-battery-48',
    domain: 'source',
    category: 'BATTERY',
    name: { ar: 'بنك بطاريات 48 فولت', en: 'Battery Bank 48V', ku: 'بانکی پاتری 48V', tr: 'Akü Bankası 48V' },
    manufacturer: 'BYD',
    model: 'B-Box Pro 13.8',
    standards: [],
    ports: outPort,
    icon: 'BatteryFull',
    color: '#22c55e',
    sourceType: 'BATTERY',
    voltage: 48,
    phases: 1,
    ratedKva: 14,
    powerFactor: 1,
    efficiency: 0.95,
    scContributionKA: 6,
  },
  {
    id: 'src-solar-30',
    domain: 'source',
    category: 'SOLAR_PV',
    name: { ar: 'منظومة طاقة شمسية 30 كيلوواط', en: 'Solar PV Array 30kW', ku: 'سیستەمی خۆری 30kW', tr: 'Solar PV 30kW' },
    manufacturer: 'JinkoSolar',
    model: 'Tiger Neo 580W',
    standards: ['IEC 60364'],
    ports: outPort,
    icon: 'Sun',
    color: '#eab308',
    sourceType: 'SOLAR_PV',
    voltage: 800,
    phases: 1,
    ratedKva: 30,
    powerFactor: 1,
    efficiency: 0.21,
    scContributionKA: 0.04,
  },
  {
    id: 'src-inverter-30',
    domain: 'source',
    category: 'INVERTER',
    name: { ar: 'عاكس هجين 30 كيلوواط', en: 'Hybrid Inverter 30kW', ku: 'ئینڤێرتەری هایبرید 30kW', tr: 'Hibrit İnverter 30kW' },
    manufacturer: 'Huawei',
    model: 'SUN2000-30KTL',
    standards: ['IEC 60364'],
    ports: [...inPort, ...outPort],
    icon: 'Waves',
    color: '#f97316',
    sourceType: 'INVERTER',
    voltage: 400,
    phases: 3,
    ratedKva: 30,
    powerFactor: 0.99,
    efficiency: 0.985,
    scContributionKA: 0.05,
  },
  {
    id: 'src-wind-10',
    domain: 'source',
    category: 'WIND',
    name: { ar: 'توربين رياح 10 كيلوواط', en: 'Wind Turbine 10kW', ku: 'توربینی با 10kW', tr: 'Rüzgar Türbini 10kW' },
    manufacturer: 'Bergey',
    model: 'Excel 10',
    standards: [],
    ports: outPort,
    icon: 'Wind',
    color: '#0ea5e9',
    sourceType: 'WIND',
    voltage: 400,
    phases: 3,
    ratedKva: 10,
    powerFactor: 0.95,
    efficiency: 0.4,
    scContributionKA: 0.1,
  },
  {
    id: 'src-ev-22',
    domain: 'source',
    category: 'EV_CHARGER',
    name: { ar: 'شاحن سيارة كهربائية 22 كيلوواط', en: 'EV Charger 22kW', ku: 'چارجەری ئۆتۆمبیلی 22kW', tr: 'EV Şarj 22kW' },
    manufacturer: 'ABB',
    model: 'Terra AC 22',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'CarFront',
    color: '#14b8a6',
    sourceType: 'EV_CHARGER',
    voltage: 400,
    phases: 3,
    ratedKva: 22,
    powerFactor: 1,
    efficiency: 0.97,
    scContributionKA: 0,
  },
];

/** Generic electrical loads used as design endpoints. */
export const LOADS: LoadSpec[] = [
  {
    id: 'load-downlight',
    domain: 'load',
    category: 'LIGHTING',
    name: { ar: 'داون لايت LED', en: 'LED Downlight', ku: 'داون لایت', tr: 'LED Downlight' },
    manufacturer: 'Generic',
    model: '800lm 12W',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'Lightbulb',
    color: '#facc15',
    powerW: 12,
    voltage: 230,
    phases: 1,
    powerFactor: 0.95,
    demandFactor: 0.9,
    lightingType: 'DOWNLIGHT',
    lumens: 800,
    beamAngleDeg: 60,
    lengthMm: 90,
  },
  {
    id: 'load-linear',
    domain: 'load',
    category: 'LIGHTING',
    name: { ar: 'إضاءة خطية LED', en: 'LED Linear Light', ku: 'ڕووناکی هێڵی', tr: 'LED Lineer' },
    manufacturer: 'Generic',
    model: '1200lm/m 18W',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'Minus',
    color: '#fde047',
    powerW: 18,
    voltage: 230,
    phases: 1,
    powerFactor: 0.95,
    demandFactor: 0.9,
    lightingType: 'LINEAR',
    lumens: 1200,
    beamAngleDeg: 120,
    lengthMm: 1200,
  },
  {
    id: 'load-spot',
    domain: 'load',
    category: 'LIGHTING',
    name: { ar: 'سبوت لايت LED', en: 'LED Spot Light', ku: 'سپۆت', tr: 'LED Spot' },
    manufacturer: 'Generic',
    model: '600lm 10W 24°',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'Flashlight',
    color: '#fbbf24',
    powerW: 10,
    voltage: 230,
    phases: 1,
    powerFactor: 0.95,
    demandFactor: 0.85,
    lightingType: 'SPOT',
    lumens: 600,
    beamAngleDeg: 24,
    lengthMm: 80,
  },
  {
    id: 'load-magnetic',
    domain: 'load',
    category: 'LIGHTING',
    name: { ar: 'تراك مغناطيسي LED', en: 'Magnetic Track Light', ku: 'تراکی مغناتیسی', tr: 'Manyetik Ray' },
    manufacturer: 'Generic',
    model: '900lm 14W module',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'Magnet',
    color: '#eab308',
    powerW: 14,
    voltage: 230,
    phases: 1,
    powerFactor: 0.95,
    demandFactor: 0.9,
    lightingType: 'MAGNETIC',
    lumens: 900,
    beamAngleDeg: 45,
    lengthMm: 300,
  },
  {
    id: 'load-lighting',
    domain: 'load',
    category: 'LIGHTING',
    name: { ar: 'دائرة إنارة', en: 'Lighting Circuit', ku: 'سوڕی ڕووناکی', tr: 'Aydınlatma Devresi' },
    manufacturer: 'Generic',
    model: 'LED 2kW',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'Lightbulb',
    color: '#facc15',
    powerW: 2000,
    voltage: 230,
    phases: 1,
    powerFactor: 0.95,
    demandFactor: 0.9,
    lightingType: 'DOWNLIGHT',
    lumens: 800,
  },
  {
    id: 'load-socket',
    domain: 'load',
    category: 'SOCKET',
    name: { ar: 'دائرة مقابس', en: 'Socket Circuit', ku: 'سوڕی پریز', tr: 'Priz Devresi' },
    manufacturer: 'Generic',
    model: 'Sockets 3.6kW',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'Plug',
    color: '#fbbf24',
    powerW: 3600,
    voltage: 230,
    phases: 1,
    powerFactor: 0.9,
    demandFactor: 0.7,
  },
  {
    id: 'outlet-socket-single',
    domain: 'load',
    category: 'SOCKET',
    name: { ar: 'مقبس 13A', en: '13A Socket Outlet', ku: 'پریزی 13A', tr: '13A Priz' },
    manufacturer: 'Legrand',
    model: 'Mosaic 13A',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'Plug',
    color: '#eab308',
    powerW: 2300,
    voltage: 230,
    phases: 1,
    powerFactor: 0.9,
    demandFactor: 0.4,
    outletKind: 'socket',
  },
  {
    id: 'outlet-socket-double',
    domain: 'load',
    category: 'SOCKET',
    name: { ar: 'مقبس مزدوج 13A', en: '13A Double Socket', ku: 'پریزی دووانە', tr: 'Çift 13A Priz' },
    manufacturer: 'Legrand',
    model: 'Mosaic 2×13A',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'Plug',
    color: '#ca8a04',
    powerW: 3600,
    voltage: 230,
    phases: 1,
    powerFactor: 0.9,
    demandFactor: 0.35,
    outletKind: 'double_socket',
  },
  {
    id: 'outlet-washer',
    domain: 'load',
    category: 'APPLIANCE',
    name: { ar: 'غسالة', en: 'Washing Machine', ku: 'جلشو', tr: 'Çamaşır Makinesi' },
    manufacturer: 'Bosch',
    model: 'Serie 6 2.2kW',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'WashingMachine',
    color: '#94a3b8',
    powerW: 2200,
    voltage: 230,
    phases: 1,
    powerFactor: 0.95,
    demandFactor: 0.8,
    outletKind: 'washer',
  },
  {
    id: 'outlet-dryer',
    domain: 'load',
    category: 'APPLIANCE',
    name: { ar: 'مجفف', en: 'Tumble Dryer', ku: 'وشککەرەوە', tr: 'Kurutma Makinesi' },
    manufacturer: 'Bosch',
    model: '2.5kW',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'Wind',
    color: '#64748b',
    powerW: 2500,
    voltage: 230,
    phases: 1,
    powerFactor: 0.95,
    demandFactor: 0.8,
    outletKind: 'dryer',
  },
  {
    id: 'outlet-dishwasher',
    domain: 'load',
    category: 'APPLIANCE',
    name: { ar: 'غسالة صحون', en: 'Dishwasher', ku: 'قاپشۆر', tr: 'Bulaşık Makinesi' },
    manufacturer: 'Bosch',
    model: '2.1kW',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'UtensilsCrossed',
    color: '#475569',
    powerW: 2100,
    voltage: 230,
    phases: 1,
    powerFactor: 0.95,
    demandFactor: 0.75,
    outletKind: 'dishwasher',
  },
  {
    id: 'outlet-oven',
    domain: 'load',
    category: 'APPLIANCE',
    name: { ar: 'فرن', en: 'Built-in Oven', ku: 'فڕن', tr: 'Fırın' },
    manufacturer: 'Siemens',
    model: '3.5kW',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'Flame',
    color: '#f97316',
    powerW: 3500,
    voltage: 230,
    phases: 1,
    powerFactor: 1,
    demandFactor: 0.7,
    outletKind: 'oven',
  },
  {
    id: 'outlet-fridge',
    domain: 'load',
    category: 'APPLIANCE',
    name: { ar: 'ثلاجة', en: 'Refrigerator', ku: 'ساردکەرەوە', tr: 'Buzdolabı' },
    manufacturer: 'Samsung',
    model: '150W avg',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'Refrigerator',
    color: '#38bdf8',
    powerW: 150,
    voltage: 230,
    phases: 1,
    powerFactor: 0.85,
    demandFactor: 0.9,
    outletKind: 'fridge',
  },
  {
    id: 'outlet-cooker',
    domain: 'load',
    category: 'APPLIANCE',
    name: { ar: 'موقد كهربائي', en: 'Electric Cooker', ku: 'مەگەس', tr: 'Elektrikli Ocak' },
    manufacturer: 'Beko',
    model: '7.4kW',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'CookingPot',
    color: '#ef4444',
    powerW: 7400,
    voltage: 230,
    phases: 1,
    powerFactor: 1,
    demandFactor: 0.6,
    outletKind: 'cooker',
  },
  {
    id: 'outlet-water-heater',
    domain: 'load',
    category: 'APPLIANCE',
    name: { ar: 'سخان مياه', en: 'Water Heater', ku: 'گەرمکەری ئاو', tr: 'Su Isıtıcısı' },
    manufacturer: 'Ariston',
    model: '3kW',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'Droplets',
    color: '#0ea5e9',
    powerW: 3000,
    voltage: 230,
    phases: 1,
    powerFactor: 1,
    demandFactor: 0.65,
    outletKind: 'water_heater',
  },
  {
    id: 'load-motor',
    domain: 'load',
    category: 'MOTOR',
    name: { ar: 'محرك ثلاثي الأطوار', en: 'Three-phase Motor', ku: 'مۆتۆری سێ فاز', tr: 'Üç Fazlı Motor' },
    manufacturer: 'WEG',
    model: '7.5kW IE3',
    standards: ['IEC 60364'],
    ports: inPort,
    icon: 'Cog',
    color: '#f59e0b',
    powerW: 7500,
    voltage: 400,
    phases: 3,
    powerFactor: 0.85,
    demandFactor: 1,
  },
  {
    id: 'load-distribution-board',
    domain: 'load',
    category: 'PANEL',
    name: { ar: 'لوحة توزيع فرعية', en: 'Sub Distribution Board', ku: 'تابلۆی دابەشکردن', tr: 'Tali Dağıtım Panosu' },
    manufacturer: 'Generic',
    model: 'SDB 40kW',
    standards: ['IEC 60364'],
    ports: [...inPort, ...outPort],
    icon: 'LayoutGrid',
    color: '#fb923c',
    powerW: 40000,
    voltage: 400,
    phases: 3,
    powerFactor: 0.9,
    demandFactor: 0.8,
  },
];
